config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :photos do
      resources :comments
      post :confirm, on: :collection
  end

  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]

  resources :relationships, only:[:create, :destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]

    def create
      # Photoをパラメータの値から探し出し,Photoに紐づくcommentsとしてbuildします。
      @comment = current_user.comments.build(comment_params)
      @photo = @comment.photo #コメントに紐づいているphotoテーブルを呼び出し
      # binding.pry

  # クライアント要求に応じてフォーマットを変更
     respond_to do |format|
        if @comment.save
          format.html { redirect_to photos_path(@comment), notice: 'コメントを投稿しました。' }
          # JS形式でindexアクションを返す
          format.js {render :index}
        else
          format.html { render :new }
        end

      end

    end

# コメントの編集
    def edit
      # binding.pry
      # コメントのフラグをtrueにする
      @comment_edit = true
      render :index
    end

    def update
      # クライアント要求に応じてフォーマットを変更
      # binding.pry
        respond_to do |format|
          if @comment.update(comment_params)
            format.html { redirect_to photos_path(@comment), notice: 'コメントを更新しました。' }
            # JS形式でindexアクションを返す
            format.js {render :index}
          else
            format.html { render :new }
          end
        end
    end

#コメントの削除
    def destroy
      #binding.pry
      @photo =  @comment.photo
      # @comment.destroy
      #クライアントの要求に応じてフォーマットを変更する(respond_toメソッドを使用)
      respond_to do |format|
        if @comment.destroy
          format.html {redirect_to photo_path(@photo)}
          # JS形式でスクリプトを返す=>JS形式のViewファイルが利用できる
          format.js {render :index}
        else
          format.html {render :new}
        end
      end
    end

private
  # ストロングパラメーター
  def comment_params
    params.require(:comment).permit(:photo_id, :content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
    @photo = @comment.photo
  end

  def set_edit
    @comment_edit = false
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([photo,comment], remote:true) do |f| %>

  <!-- 下のhidden_fieldを入れないとcommentテーブルのphoto_idが格納されない-->
  <%= f.hidden_field :photo_id %>

  <div class="field">
    <!-- この段階でcommentテーブルのphoto_idは入っている-->

    <!--コメントのコンテンツがないかどうかの確認-->
    <% if comment.content.blank? %>
      <%= f.text_field :content, placeholder: "内容", class: "form-control btn-default"  %>
    <% else %>
      <!-- <p>neko</p> -->
      <%= f.text_field :content ,placeholder: "内容", class: "form-control btn btn-default"  %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
      <%# binding.pry %>
      <% unless comment.id.nil? %>
        <li>
          <p class="left"><%= comment.user.name %>さんがコメントしました。</p>

          <!--編集ボタンが押された時の動作:コメントidが一致するかどうか-->
          <% if comment.id == @comment.id  && @comment_edit == true %>
            <%= render partial: 'comments/form', locals: { comment: comment, photo: @photo } %>
          <% else %>
            <!-- コメント内容の表示 -->
            <p class="left"><%= comment.content %></p>
          <% end %>

          <% if current_user.id == comment.user.id %>
            <p class="right">
              <%= link_to '', edit_photo_comment_path(photo, comment), class: "fa fa-pencil-square-o fa-lg", method: :get, remote: true  %>
              <%= link_to '', photo_comment_path(photo, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true %>
            </p>
          <% end %>
        </li>
      <% end %>
    <% end %>
</ul>

app/views/comments/index.js.erb
// var id_num = 1;
// var id_name = "#comments_area" + id_num
$("#comments_area_"+"<%= @photo.id %>").html("<%= j(render 'comments/index', { comments: @comment.photo.comments, photo: @comment.photo }) %>")
console.log

// if (<% @comment.content.blank? %> == true) {
$(':text').val('')
// }