config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :photos do
      resources :comments
      post :confirm, on: :collection
  end

  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]

  resources :relationships, only:[:create, :destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #UserクラスをPhotoクラスへ紐付けしユーザーを削除すると当該のPhotoカラムを削除する
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Userモデルが複数のrelationshipを持つ
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  # Relationshipモデルに対してreverse_relationshipsという紐付けを定義
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy

  # UserモデルがRelationshipモデルを介して複数のUserを持つ
  #
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  mount_uploader :avatar,PhotoUploader  #アップローダーの設定

  validates :name, presence: true #バリデーションの設定


  #指定のユーザをフォローする
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  #フォローしているかどうかを確認する
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  #ランダムなuidを作成するメソッド
  def self.create_unique_string
    SecureRandom.uuid
  end

  # update_with_passwordのオーバーライド
  def update_with_password(params, *options)
    #ユーザーテーブルのproviderカラムの中身が空かどうか
    if provider.blank?
      # binding.pry
      super
    else
      params.delete :current_password
      # binding.pry
      update_without_password(params, *options)
    end
  end


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
      user = User.find_by(email: auth.info.email)

      unless user
         user = User.new(
              name:     auth.extra.raw_info.name,
              provider: auth.provider,
              uid:      auth.uid,
              email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
              image_url:   auth.info.image,
              password: Devise.friendly_token[0, 20]
             )
             user.skip_confirmation!
             user.save(validate: false)
      end
      user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
  user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
  # You need to implement the method below in your model
  @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show

    #binding.pry
    @followed_users = @user.followed_users
    @followers = @user.followers

  end

  private

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registations_helper.rb
module Users::RegistationsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "友達になる", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "取り消し", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー一覧</h2>
  <% @users.each do |user| %>
      <!-- <div class="container-child col-md-2 col-sm-4 col-xs-6 "> -->
        <!-- <p><%= link_to user.name, user_path(user), method:'get' %></p>
        <%= user.email %>
        <%= render 'follow_form', user: user %> -->
      <!-- <div class="container-child col-md-2 col-sm-4 col-xs-6 "> -->
      <% if user.id != current_user.id %>
      <ul class="user_index">
        <li class="user_profile">
           <%= profile_img(user) %>
          <div class="user_name">
            <%= link_to "#{user.name}さん", user %>
            <br/>
            <%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
            <%= render partial: 'follow_form', locals: { user: user } if signed_in?%>
          </div>
        </li>
      </ul>
      <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>このユーザーについて</h1>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <%= profile_img(@user) %>
        <p> プロフィール画像 </p>
        <p>メールアドレス：<%= @user.email %></p>
        <!-- <%# binding.pry %> -->
      </div>

        <p>フォローされているユーザー</p>
          <% @followers.each do |follower| %>
          <% if follower.image_url %>
            <%= image_tag(follower.image_url, alt: follower.name, :size => "40x40") %>
          <% end %>
            <!-- フォロワーの表示　-->
            <%= link_to(follower.name, user_path(follower.id)) %>
            <!-- フォローしたユーザーの表示 -->
            <%#= user.followers.find(3).name %>
            <br/>
          <% end %>

          <p>フォローしているユーザー</p>
          <% @followed_users.each do |followed_user| %>
            <% if followed_user.image_url %>
              <%= image_tag( followed_user.image_url, alt: followed_user.name, :size => "40x40") %>
            <% end %>

              <!-- フォローしたユーザーの表示 -->

              <%= link_to(followed_user.name, user_path(followed_user.id)) %>
              <br/>
          <% end %>
</div>