config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :photos do
      resources :comments
      post :confirm, on: :collection
  end

  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]

  resources :relationships, only:[:create, :destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  #アソシエーションの設定
  belongs_to :user
  #写真が削除されたらコメントも同時に削除する
  has_many :comments, dependent: :destroy

  # validates :name, :content, :photo, presence: true #バリデーションの設定(旧)
  validates :content, presence: true #バリデーションの設定
  mount_uploader :photo,PhotoUploader  #carrierwaveの設定
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #ログインしていなければ投稿機能を使用できないようにする(Deviseのauthenticate_user!メソッドを使用)
  before_action :authenticate_user!

  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  # before_action :check_user

  # GET /photos
  def index
    @photos = Photo.all
    # render action: :show #これはshowのviewを表示するだけ(showアクションは発生しない)
  end

  # 確認
  def show
    # @comment = @photo.comments.build
    #@comments = @photo.comments
  end


  # 新規作成
  # GET /photos/new
  def new

    if params[:back]
      @photo =  Photo.new(photo_params)
    else
      @photo = Photo.new
    end

  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    @photo.user_id = current_user.id #user_idカラムにユーザーidを格納

      #photoテーブルの書き込み時の処理
      if @photo.save
        redirect_to photos_url, notice: '投稿が完了しました'
        # render :show, status: :created, location: @photo
      else
        render :new
      end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_url, notice: '更新が完了しました' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: '写真の削除が完了しました' }
    end
  end

  private

    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :content, :user_id, :photo)
    end

end

app/helpers/photos_helper.rb
module PhotosHelper

  # プロフィール画像が登録されているかどうかチェックする
  def profile_photo_checker(photo)

    if @photos.find(photo.id).user.image_url &&  @photos.find(photo.id).user.avatar
      # プロフィールとSNS画像が共に格納されてた場合は登録画像を表示
      return image_tag(@photos.find(photo.id).user.image_url, :size => "40x40")
    elsif  @photos.find(photo.id).user.image_url
      #　SNS画のみ格納されてた場合は登録画像を表示
      return image_tag(@photos.find(photo.id).user.image_url, :size => "40x40")
    else
      # 登録がなければno_imageを表示
      return image_tag("no_image.png", :size => "40x40")
    end

  end

  def photo_checker(photo)
    # binding.pry
    if !photo.photo.model.photo.blank?
        return image_tag(photo.photo,:size => "400x400")
    end

  end

end

app/views/photos/_form.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

    <%= form_for(@photo) do |f| %>
      <%= f.error_messages! %>

      <!-- <div class="field">
        <%#= f.text_field :name, placeholder:"タイトル", class:'form-control' %>
      </div>
      <br/> -->

      <div class="field content">
        <!--プロフィール画像が登録されいるかどうか判断-->
        <% if !@photo.photo.model.photo.blank? %>
        <!-- 画像がない場合 画像を表示させず適用させるクラスを変更-->
          <%= image_tag(@photo.photo, :size => "40x40", class: "content_photo") %>
          <%= f.text_field :content , placeholder:"今何してる？", class:'form-control content_text_validimage' %>
        <% else %>
          <%= f.text_field :content , placeholder:"今何してる？", class:'form-control content_text' %>
        <% end %>

      </div>

      <br/>

      <div class="field">
        <!-- <＃%= profile_img(@photo) if profile_img(@photo) %> -->
          <% if @photo.photo.model.photo.blank? %>
                <!-- <%# binding.pry %> -->
                <h3>画像を投稿する</h3>
                <!-- <%= image_tag(@photo.photo, :size => "200x200")%> -->
                <%= f.file_field :photo, class: "btn " %>
                <%= f.hidden_field :photo_cache %>
          <% else %>
                <!-- <%# binding.pry %> -->
                <h3>画像を更新する</h3>
                <%= image_tag(@photo.photo, :size => "200x200")%>
                <%= f.file_field :photo %>
                <!-- <%= f.hidden_field :photo_cache %> -->
          <% end %>
      </div>

      <div class="actions">
        <%= f.submit "投稿する", method:'post', class:'btn btn-block btn-primary'%>
      </div>

      <br/>
      <%= button_to '戻る', photos_path, method: "get", class: "btn btn-block btn-primary" %>
    <% end %>

  </div>
</div>

app/views/photos/_show.html.erb
<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, photo: @photo } %>
</div>
<%= render partial: 'comments/form', locals: { comment: @comment, photo: @photo } %>
<% if current_user.id == @photo.user_id %>
  <%#= link_to '編集', edit_photo_path(@photo) %> |
<% end %>

app/views/photos/edit.html.erb
<h1>投稿を編集する</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<p class="flash"> <%= notice %> </p>

<h1>投稿一覧</h1>

<div class="container col-md-8 col-md-offset-2">
  <!-- <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1"> -->

  <%= button_to '新規投稿', new_photo_path, method:'get', class:"btn btn-default" %>

<div class = "main col-xs-12">

     <!--投稿の大枠-- >
    <div class = "contribution">

    <!--　最新の投稿から表示　-->
    <% @photos.order("created_at DESC").each do |photo| %>

          <!-- <＃% binding.pry %> -->
          <div class = "contribution_name">
            <!-- <%#= profile_img(Photo.find(photo.id).user) %> -->
            <!-- <%#= image_tag(@photos.find(photo.id).user.image_url, :size => "40x40")%> -->
            <%= profile_photo_checker(photo) %>
            <%= link_to photo.user.name, user_path(photo.user.id), method:'get' %>さん
            <br/>
            <%= contribution_time(photo.created_at) %>に投稿
            <br/>
            <%= link_to("詳細", photo_path(photo.id), method: :get)%>
            <!-- <%#= link_to '', edit_photo_comment_path(photo, comment), class: "fa fa-pencil-square-o fa-lg", method: :get, remote: true  %> -->
          </div>
          <div class = "contribution_text">
            <%= photo.content %>
          </div>


          <div class = "contribution_image">
            <%= photo_checker(photo) %>
          </div>

          <!-- コメント入力欄-->
          <!-- アプリケーションヘルパーから呼び出し-->
          <% comment_form(Photo.find(photo.id)) %>
           <!-- コメント入力のビューを表示-->
          <%#= render 'show' %>

          <div id="comments_area_<%= photo.id %>">
            <%= render partial: 'comments/index', locals: { comments: @comments, photo: @photo } %>
          </div>
            <%= render partial: 'comments/form', locals: { comment: @comment, photo: @photo } %>

          <% if current_user.id == @photo.user_id %>
                <%= button_to '投稿を編集', edit_photo_path(photo),method: 'get', class: "btn btn-primary" %>
                <%= button_to '投稿を削除', photo_path(photo), method: 'delete',data: { confirm: '本当に削除しますか？'}, class:"btn  btn-danger" %>
          <% end %>

        <% end %>
      </div>

          <!-- <%#= button_to '編集', edit_photo_path(photo), method:'get', class:"btn btn-block btn-info" %> -->

    </div>

</div>
<br/>

app/views/photos/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<h2> 投稿詳細　</h2>

<div class="container" >
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

  <div class = "contribution_name">
    <%= profile_img(Photo.find(@photo.id).user) %>
    <p>投稿者：<%= link_to @photo.user.name, user_path(@photo.user.id), method:'get' %>さん</p>
    <%= contribution_time(@photo.created_at) %>に投稿
    <br/>
    <!-- <%#= link_to '', edit_photo_comment_path(photo, comment), class: "fa fa-pencil-square-o fa-lg", method: :get, remote: true  %> -->
  </div>

    <h3> 投稿内容 </h3>
  <div class = "contribution_text">
    <%= @photo.content %>
  </div>




  <!-- コメント入力欄-->
  <!-- アプリケーションヘルパーから呼び出し-->
  <h3>コメント一覧</h3>
  <% comment_form(Photo.find(@photo.id)) %>
   <!-- コメント入力のビューを表示-->
  <%#= render 'show' %>

  <div id="comments_area_<%= @photo.id %>">
    <%= render partial: 'comments/index', locals: { comments: @comments, photo: @photo } %>
  </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, photo: @photo } %>

  <% if current_user.id == @photo.user_id %>
        <p><%= button_to '投稿を編集', edit_photo_path(@photo),method: 'get', class: "btn btn-primary" %></p>
        <%= button_to '投稿を削除', photo_path(@photo), method: 'delete',data: { confirm: '本当に削除しますか？'}, class:"btn  btn-danger" %>
  <% end %>

  <br/>
  <%= button_to("投稿一覧へ戻る", photos_path, method: 'get', class: "btn btn-primary btn-block")%>
  <br/>
  
 </div>
</div>