config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :photos do
      resources :comments
      post :confirm, on: :collection
  end

  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]

  resources :relationships, only:[:create, :destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!-- 共通のビューファイル -->
<!DOCTYPE html>
<html>
<head>
  <title>Clonebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true, :debug => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, :debug => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- スマホやタブレットで崩れないようにするために書く-->
</head>

<body>

<header>
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- サインイン時は投稿ページにリンクする -->
      <% if !user_signed_in? %>
        <%= link_to "Clonebook", root_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "Clonebook", photos_path, class: "navbar-brand" %>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> -->
          <!-- <ul class="dropdown-menu">
            <li><%= link_to "投稿", photos_path %></li>
          </ul> -->
          <li><%= link_to "投稿", photos_path %></li>

          <!--ログインの確認deviseの[user_signed_in?]メソッドを利用し判定処理-->
          <% if user_signed_in? %>
            <li><%= link_to 'マイページ', edit_user_registration_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'ユーザー一覧', users_path %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path  %></li>
            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
          <% end %>

          <!-- </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>
</header>


<%= yield %>

<br/>
<footer>
  <p>© 2015-2016 Copyright Yoshimitsu Hama  </p>
</footer>

</body>
</html>